### ISSUE TITLE
Tests fail on new range-spec test cases (after 2016)

### ISSUE THREAD

**Issue by bohan-zhang** [square/grange#37]
The test cases fail with range-spec queries updated after February 2016.

```
a - {}
a

a, {}
a

a - ()
a

a, ()
a

%()

%{}

mem(GRO{UPS};host2)
dc1
```

Also, from the tests I got this bug report:
```
got: Set{bc}
want: Set{two, both, one}

got: Set{c}
want: Set{one, two, both}

Could not parse query: %de{f}:KEYS

expand_test.go:86: FAILED /range-spec/spec/expand/numeric_expansion.spec:31
got: Set{an1, an2, an3, an1..n03}
want: Set{an1, an2, an3}

expand_test.go:86: FAILED /range-spec/spec/expand/numeric_expansion.spec:55
got: Set{a1a1..a1a3, a1a1a3}
want: Set{a1a1, a1a2, a1a3}

expand_test.go:86: FAILED /range-spec/spec/expand/numeric_expansion.spec:61
got: Set{a2a2a1..a2a2, a2a2a1a2, a2a2a2a2}
want: Set{a2a2a1, a2a2a2}

expand_test.go:78: FAILED /range-spec/spec/expand/parsing.spec:8
Could not parse query: %a.b

expand_test.go:86: FAILED /range-spec/spec/expand/regex.spec:10
got: Set{}
want: Set{bad, mad}

expand_test.go:78: FAILED /range-spec/spec/expand/clusters/cluster_dots.spec:1
Could not parse query: %a.b.c

expand_test.go:78: FAILED /range-spec/spec/expand/clusters/cluster_dots.spec:16
Could not parse query: %a.b-c.d

expand_test.go:78: FAILED /range-spec/spec/expand/clusters/cluster_func.spec:1
Could not parse query: %allclusters()

expand_test.go:86: FAILED /range-spec/spec/expand/default_cluster/at_operator.spec:8
got: Set{cure}
want: Set{host1}

expand_test.go:78: FAILED /range-spec/spec/expand/default_cluster/mem_function.spec:1
Unknown function: mem

expand_test.go:78: FAILED /range-spec/spec/expand/default_cluster/mem_function.spec:5
Unknown function: mem

expand_test.go:86: FAILED /range-spec/spec/expand/dollar_sign/dollar_operator.spec:2
got: Set{bar2, bar1}
want: Set{$foo}
```

**Comment by xaviershay** [comment]
thanks for this report and the other one. I'll try to find some time to take a look over the weekend!

**Comment by bohan-zhang** [comment]
@xaviershay Thank you for looking it over! All the errors have been listed above.

**Comment by xaviershay** [comment]
hrm that's really surprising that so many are failing, feels like something must be pretty busted - but hopefully just one systemic issue.

**Comment by xaviershay** [comment]
or I mean maybe it is really just that we never updated this project to support those cases!?

**Comment by bohan-zhang** [comment]
@xaviershay The common issue I saw is `runtime error: index out of range` in `grange.(*rangeQuery).addOperator`. Also, the diff of test cases is attached.
[diff.txt](https://github.com/square/grange/files/2362223/diff.txt)

**Comment by bohan-zhang** [comment]
@xaviershay I believe so. It seems that range-spec added more cases after February 2016.

**Comment by xaviershay** [comment]
hrm that diff doesn't include some of the ones that are failing (regex, dollar). Curious.

**Comment by bohan-zhang** [comment]
@xaviershay oh the diff is based on what I removed to make the tests run

**Comment by xaviershay** [comment]
Actually there's a really easy hack - can just insert a dedicated rule for empty brackets.

**Comment by xaviershay** [comment]
closing in favour of https://github.com/square/grange/pull/39
